package com.pmgohil.resumecenter

data class UserDataModel(

    var name: String? = null,
    var email: String? = null,
    var number: String? = null,
    var address: String? = null,
    var gender: String? = null,
    var birthDate: String? = null,
    var birthPlace: String? = null,
    var religion: String? = null,
    var cast: String? = null,
    var maritialStatus: String? = null,
    var child: String? = null,
    var languageKnown: String? = null,
    var otherLanguageKnown: String? = null,
    var website: String? = null,
    var nationality: String? = null,
    var vilage: String? = null,
    var taluka: String? = null,
    var district: String? = null,
    var state: String? = null,
    var country: String? = null
)

data class EducationDataModel(
    var schoolName10: String? = null,
    var schoolAddress10: String? = null,
    var contact10: String? = null,
    var degreeName10: String? = null,
    var percentage10: String? = null,
    var passingYear10: String? = null,
    var schoolName12: String? = null,
    var schoolAddress12: String? = null,
    var contact12: String? = null,
    var streamRadio: String? = null,
    var degreeName12: String? = null,
    var passingYear12: String? = null,
    var percentage12: String? = null,
    var universityNameGraduation: String? = null,
    var collegeNameGraduation: String? = null,
    var collegeAddressGraduation: String? = null,
    var contactGraduation: String? = null,
    var degreeNameGraduation: String? = null,
    var percentageGraduation: String? = null,
    var passingYearGraduation: String? = null,
    var universityNamePostGraduation: String? = null,
    var collegeNamePostGraduation: String? = null,
    var collegeAddressPostGraduation: String? = null,
    var contactPostGraduation: String? = null,
    var degreeNamePostGraduation: String? = null,
    var percentagePostGraduation: String? = null,
    var passingYearPostGraduation: String? = null,
    var otherDegreeName1: String? = null,
    var otherDegreePercentage1: String? = null,
    var otherDegreePassingYear1: String? = null,
    var otherDegreeName2: String? = null,
    var otherDegreePercentage2: String? = null,
    var otherDegreePassingYear2: String? = null,
)

data class SkillDataModel(
    var SkillName1: String? = null,
    var SkillName2: String? = null,
    var SkillName3: String? = null,
    var SkillName4: String? = null,
    var SkillName5: String? = null,
    var SkillName6: String? = null,
    var SkillName7: String? = null,
    var SkillName8: String? = null,
    var SkillName9: String? = null,
    var SkillName10: String? = null
)

data class ExperienceDataModel1(
    var Fresher: String? = null
)

data class ExperienceDataModel(
    var JobTitle1: String? = null,
    var Position1: String? = null,
    var CompanyName1: String? = null,
    var Location1: String? = null,
    var JobTitle2: String? = null,
    var Position2: String? = null,
    var CompanyName2: String? = null,
    var Location2: String? = null,
    var JobTitle3: String? = null,
    var Position3: String? = null,
    var CompanyName3: String? = null,
    var Location3: String? = null,
    var JobTitle4: String? = null,
    var Position4: String? = null,
    var CompanyName4: String? = null,
    var Location4: String? = null,
    var JobTitle5: String? = null,
    var Position5: String? = null,
    var CompanyName5: String? = null,
    var Location5: String? = null,
    var JobTitle6: String? = null,
    var Position6: String? = null,
    var CompanyName6: String? = null,
    var Location6: String? = null,
    var JobTitle7: String? = null,
    var Position7: String? = null,
    var CompanyName7: String? = null,
    var Location7: String? = null,
    var JobTitle8: String? = null,
    var Position8: String? = null,
    var CompanyName8: String? = null,
    var Location8: String? = null,
    var JobTitle9: String? = null,
    var Position9: String? = null,
    var CompanyName9: String? = null,
    var Location9: String? = null,
    var JobTitle10: String? = null,
    var Position10: String? = null,
    var CompanyName10: String? = null,
    var Location10: String? = null
)

data class ReferenceDataModel(
    var Name1Reference: String? = null,
    var CompanyName1Reference: String? = null,
    var Position1Reference: String? = null,
    var Phone1Reference: String? = null,
    var Location1Reference: String? = null,
    var Name2Reference: String? = null,
    var CompanyName2Reference: String? = null,
    var Position2Reference: String? = null,
    var Phone2Reference: String? = null,
    var Location2Reference: String? = null,
    var Name3Reference: String? = null,
    var CompanyName3Reference: String? = null,
    var Position3Reference: String? = null,
    var Phone3Reference: String? = null,
    var Location3Reference: String? = null,
    var Name4Reference: String? = null,
    var CompanyName4Reference: String? = null,
    var Position4Reference: String? = null,
    var Phone4Reference: String? = null,
    var Location4Reference: String? = null,
    var Name5Reference: String? = null,
    var CompanyName5Reference: String? = null,
    var Position5Reference: String? = null,
    var Phone5Reference: String? = null,
    var Location5Reference: String? = null,
    var Name6Reference: String? = null,
    var CompanyName6Reference: String? = null,
    var Position6Reference: String? = null,
    var Phone6Reference: String? = null,
    var Location6Reference: String? = null,
    var Name7Reference: String? = null,
    var CompanyName7Reference: String? = null,
    var Position7Reference: String? = null,
    var Phone7Reference: String? = null,
    var Location7Reference: String? = null,
    var Name8Reference: String? = null,
    var CompanyName8Reference: String? = null,
    var Position8Reference: String? = null,
    var Phone8Reference: String? = null,
    var Location8Reference: String? = null,
    var Name9Reference: String? = null,
    var CompanyName9Reference: String? = null,
    var Position9Reference: String? = null,
    var Phone9Reference: String? = null,
    var Location9Reference: String? = null,
    var Name10Reference: String? = null,
    var CompanyName10Reference: String? = null,
    var Position10Reference: String? = null,
    var Phone10Reference: String? = null,
    var Location10Reference: String? = null
)
